### ISSUE TITLE
BeebUtils.pm wrongly errors with "Not enough space"

### ISSUE THREAD

**Issue by lurkio** [sweharris/split_md_dsd#4]
The linked .DSD (below) causes BeebUtils.pm (via split_md_dsd) to error, claiming there's "Not enough space to add $.FINDATA", but there should in fact be enough space to add the file. (The actual game to which the file belongs (Chart Challenge 88) doesn't actually work, but that's not the issue here.)

https://github.com/lurkio/split_md_dsd/blob/d22d06cd941a6f025aa9c51f44c5a75fd511d302/Disc134.dsd

**Comment by lurkio** [comment]
Ignore. 

My mistake. I think.

**Comment by sweharris** [comment]
Is this because the disk was 100% full and so not enough space for a !BOOT ?

If you think it would help, maybe I can catch this error and delete the !BOOT, same as we do for catalogue full issues...

**Comment by sweharris** [comment]
Actually that sounded like a good idea, anyway, so I did it.  So now if the catalogue is full or the disk doesn't have enough free sectors then we'll delete !BOOT and retry
